### ISSUE TITLE
Homekit automation thermostat auto

### ISSUE THREAD

**Issue by davyd15** [lukasroegner/homebridge-tado#25]
if i setup an automation in homekit that the thermostat is set to auto when i close my window(with eve window sensor), the thermostat is always set to heating instead to auto. is there a solution for this?

**Comment by RamBumBada** [comment]
Same effect under same conditions. I use also the Eve window sensors and created an automation to set thermostat to auto on closing the window. But the Thermostat, the Tado App and the Eve/Home App shows following: The Temperatur seems to be set manual and infinity, no timer to next autmation time block.

**Comment by darrenmcuk** [comment]
I am struggling with the same concept...
I have tried "auto in next time block" to see if that does it...but I don't think it quite does

**Comment by benno666** [comment]
Unfortunately, I haven‘t found a quick solution for this either. Since iOS 13, if you use an automation in HomeKit to change the thermostat‘s status from off to auto, HomeKit sends a target temperature, too, thus the plugin will go into manual mode. It is not possible to delete the target temperature in HomeKit automations anymore. And there‘s no workaround I know of using third-party HomeKit apps, because they have no access to alter HomeKit automations.

That‘s why I use two scenes instead: One solely activates the auto mode if the window is closed, another one turns the thermostat off if the window is open. In scenes you can set the parameters as you wish!

However, one could change the plugins behaviour towards this, i.e. it could ignore the target temperature when you set the auto mode at the same time (using an automation). But I’m afraid that‘s not quite simple.

**Comment by lukasroegner** [comment]
I had a similar issue with the Dyson Pure Cool plugin, where HomeKit always switched to AUTO mode when switching the device on...I applied the same technique here, so setting to AUTO mode in HomeKit automations should work now (version 0.7.0).

**Comment by benno666** [comment]
Somehow I found a way to solve this use-case with the plugin's HTTP API. It was there the whole time and I didn't see it...

If my window sensor detects an open window, I now use a shortcut in HomeKit to use a POST using the HTTP API and hereby setting the thermostat to "off". If the window is closed, the thermostat is set to "auto". This way there is no struggle using the "regular" HomeKit automations.
