### ISSUE TITLE
Tado App Schedule „Off“ - not in Homekit

### ISSUE THREAD

**Issue by Kohle81** [lukasroegner/homebridge-tado#4]
Hello Lukas, when testing your plugin I noticed the following: In the tado app I currently have the heating "off" in the stored schedules and it shows frost protection.  In the home app, however, "set to 5 degrees" is still displayed.  Only when I set "Off" in Home will the status in Off be set to "Off".  Then the automatic mode at tado is ended.  It's not really bad, I just wanted to tell you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lukasroegner** [comment]
Hi @Kohle81, I thought about that when implementing the plugin. The issue is that HomeKit does not support OFF in AUTO mode. There were two possible options

**5 degrees as OFF in HomeKit when a Tado zone is in AUTO mode**
Pros: You can see the actual state of the zone (MANUAL or AUTO) in HomeKit
Cons: 5 degrees is not the actual target temperature

**OFF in HomeKit when Tado is in AUTO mode and "target temperature" is set to OFF**
Pros: HomeKit displays the correct "target temperature" (i.e. OFF when the zone is OFF)
Cons: HomeKit does not tell you whether Tado is in AUTO mode when set to OFF (could be a MANUAL or AUTO OFF)

I chose to implement the first option, as it was more important to me that I can see the correct mode (AUTO/MANUAL) in HomeKit. Do you think the second option does make more sense to implement?

**Comment by Kohle81** [comment]
I can fully understand your thoughts and it would be fine for me too.  Is it possible to determine the display in the config using true / false?  Alternatively, I could also imagine from May 1st to September 30th.  set the display so that in HomeKit is "Off", since most heaters are not used (ok depending on the time zone 😬😬😬) and the Auto mode is only set to Off in the schedule ...... If it is  However, too much work means, please do not see my advice as a criticism, but as an exchange of ideas - it is a great plugin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lukasroegner** [comment]
Hi @Kohle81, I went through the code once more to check whether there might be a solution to the original problem, however, there is not. The plugin already reports Current State = OFF to HomeKit, however, in AUTO mode, the Home app still displays "set to X degree", even if Current State = OFF.

I don't know your exact configuration of Tado, however, I can tell you how I handle the summer times: I just set all thermostats to manual OFF (indefinitely) in the Tado app. Thus, they are also shown as OFF in HomeKit. This works for me, as the main heating is switched off in the summer times by the landlord, which means, even if there would be a schedule, it would just make no sense and would not heat at all.

**Comment by Kohle81** [comment]
Thanks for checking.  This workaround with manual switch-off is also a good alternative solution for me.  From that point of view it is completely fine for me.  Thank you for your time!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benno666** [comment]
@lukasroegner @Kohle81 
Sorry if I have to ask, but is there a need to have the thermostat set to off when you‘re in auto mode? What‘s your use case for this? Wouldn‘t it be sufficient to switch to manual mode when turning the thermostat off?

**Comment by Kohle81** [comment]
If I switch the heating off manually via tado, Homekit shows me "set to 5 degrees".  So I switch it on again manually in Homekit.  Automatic mode is not required here because the season is warm.

> Am 08.05.2020 um 19:40 schrieb benno666 <notifications@github.com>:
> 
> Sorry if I have to ask, but is there a need to have the thermostat set to off when you‘re in auto mode? What‘s your use case for this? Wouldn‘t it be sufficient to switch to manual mode when turning the thermostat off?
