### ISSUE TITLE
Windows Open and Siri

### ISSUE THREAD

**Issue by solbadguy2010** [lukasroegner/homebridge-tado#47]
Hi,
I am not able to achieve the following:

1: i want to use windows open sensors. Windows open -> off until changed by user. Windows closed -> automatic mode. 

2: I wand to tell Siri to set a temp in a specific room or change it in home. Heating or cooling -> manual mode until next time block, then back to automatic. 

1 is working when „auto in next time block“ is off, 2 is working when it is on. But i am not able to mix both. 

Is this possible? If yes, how to configure it? If no, could you implement it?

**Comment by bnSonic** [comment]
this won't work as "setting back after some time / next time block" is not a HomeKit/PlugIn-Feature but a Tado-Feature.

So: The best way (IMHO) is to set Tado to "manual settings should stay until next time block"
Of course that means: If you switch off (with the help of a different window sensor), Tado may switch it back on if a next Time-Block starts…

For me this OK because my Time-Blocks almost never conflicts with the time i open the windows

**Comment by solbadguy2010** [comment]
Thats wrong, since both options are already possible with this plugin, but you have choose wich one. I want to have an mixed mode. This should be programmable, to that the Plugin send command a) to the Tado bridge when set „off“ in home and command b) when you set a manual temp. 

Your suggestion is not a good solution since if you forget to close a window you heat out of the window.

**Comment by bnSonic** [comment]
:) no, it's not wrong - but i'm not here to discuss this one out ;) If you don't believe me, that's your choice.
Maybe the developer of this plugin will teach me wrong and implement that feature - that would surprise me but i wouldn't have a problem with that :)

**Comment by solbadguy2010** [comment]
But have you read, that both is already in this plugin?

„switchToAutoInNextTimeBlock (optional): If set to true, the state of the zone is switch back to AUTO in the next time block of the time table (same behavior as the zone setting for manual changes on the device itself). Defaults to false.“

What i want to achieve, is that this setting is true for manual temps in the home app and false for off in the home app. 

If you change the value in home it sends a command to homebridge which translates it to a tado bridge command. As said, already happening. I only want an option to set the command homebridge sends to tado seperately instead of one option for both.

**Comment by benno666** [comment]
@solbadguy2010

Hi,

there's one thing that just came to my mind today because I wanted to do something similar. Would it be sufficient if you could

1. set the thermostat to off until "changed by user" (and only in this situation) and
2. use "manual settings should stay until next time block" in any other situation?

If so, you could try to use the HTTP API to switch the thermostat off using Shortcuts in HomeKit, while "switchToAutoInNextTimeBlock" is still activated and used for every other command.

**Comment by solbadguy2010** [comment]
Hi, yes, this sounds like a workaround until it is implemented in the plugin. How do you send http commands and which ones?

**Comment by benno666** [comment]
@solbadguy2010

You can create an automation in HomeKit but instead of selecting a scene or a device to be controlled, convert it to a shortcut. There you can add this:

![Bildschirmfoto 2021-04-14 um 13 24 32](https://user-images.githubusercontent.com/38656206/114703069-21b82880-9d25-11eb-923a-36afa46b4f80.png)
![Bildschirmfoto 2021-04-14 um 13 24 49](https://user-images.githubusercontent.com/38656206/114703124-31d00800-9d25-11eb-8154-29f445460b10.png)

Use your Homebridge IP as URL and - important! - keep the capitalized "HTTP://" or else there can be a SSL connection failure. Change "your-token" to the token you selected in the settings of the plugin and select the target-state (or target-temperature) of your choice. That's it!

**Comment by solbadguy2010** [comment]
Ich danke dir, das teste ich mal ;-)

thank you, will test.

**Comment by solbadguy2010** [comment]
Hi,
i just tested your solution and it works perfectly. I configured to Plugin to use "Auto in next time block" and use the windows open/close contact as trigger for a shortcut fireing the POST request.
Hint: In Eve App its easier to realise this with multiple windows per room. 
Use multiple Windows as trigger for open, then convert to shortcut in home App.
Use multiple Windows as trigger and condition for close, then convert to shortcut in Home App.

Thank you again!
